// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace interview.Models;

[Keyless]
public partial class Account
{
    public Guid? AccountGuid { get; set; }

    public Guid? OwnerGuid { get; set; }

    public int? BranchID { get; set; }

    public int? AcctSerialID { get; set; }

    public int? AccountKind { get; set; }

    [StringLength(100)]
    public string AccountName { get; set; }

    [StringLength(50)]
    public string AccountStatus { get; set; }

    [StringLength(50)]
    public string CacheTime { get; set; }
}