// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace interview.Models;

[Keyless]
public partial class NetBankUser
{
    public Guid? UserGuid { get; set; }

    [StringLength(20)]
    public string NationalID { get; set; }

    public int? UserKind { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(50)]
    public string ApplyDate { get; set; }

    [StringLength(50)]
    public string CacheTime { get; set; }

    [StringLength(50)]
    public string UpdatePasswordDate { get; set; }

    public bool? IsAlive { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SyncAccount { get; set; }
}